# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tancredi-Paul Grozav
email: paul@grozav.info
description: > # this means to ignore newlines until "baseurl:"
  Knowledge Base of Tancredi-Paul Grozav. It will appear in your document head
  meta (forGoogle search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
gitlab_username:  tancredi-paul-grozav

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]
